import { ArrowRight, BookOpenCheck, Compass, FileSearch, ShieldCheck, Sparkles } from "lucide-react";
import { SectionHeading } from "../../shared/components/SectionHeading";

const capabilities = [
  { icon: BookOpenCheck, title: "Understand your rights", text: "Explore clear, reviewed information designed around the questions students ask." },
  { icon: FileSearch, title: "Make sense of documents", text: "Learn what common clauses may mean and which details deserve a closer look." },
  { icon: Compass, title: "Find a next step", text: "See practical options and support resources so you can decide what feels right." },
];
const steps = [
  { number: "01", title: "Start with your question", text: "Choose a topic or describe what you are trying to understand." },
  { number: "02", title: "Get information in context", text: "See plain language guidance, with its limits and relevant sources made clear." },
  { number: "03", title: "Choose what comes next", text: "Review practical options and find human support when you need it." },
];

export function LandingPage() {
  return <>
    <section className="hero"><div className="page-container hero__grid"><div className="hero__copy"><p className="eyebrow"><span className="eyebrow__dot" /> A clearer place to begin</p><h1>Know your rights.<br /><span>Understand your options.</span></h1><p className="hero__lead">Student life can bring unfamiliar rules and important documents. Get clear information and find a practical next step, at your own pace.</p><div className="hero__actions"><a className="button button--primary" href="#how-it-works">Explore how it works <ArrowRight aria-hidden="true" size={18} /></a><a className="text-link" href="#our-approach">How we keep it clear</a></div><p className="hero__note"><ShieldCheck aria-hidden="true" size={16} /> Designed with privacy in mind. Information, not legal advice.</p></div>
      <div aria-label="Illustration: a student making a considered next step" className="hero-art" role="img"><div className="hero-art__glow" /><div className="hero-art__paper"><div className="hero-art__paper-title"><span /><span /></div><div className="hero-art__line hero-art__line--long" /><div className="hero-art__line" /><div className="hero-art__callout"><span className="hero-art__check"><ShieldCheck aria-hidden="true" size={19} /></span><span><strong>A good place to start</strong><small>Clear information, one step at a time</small></span></div><div className="hero-art__line hero-art__line--short" /></div><div className="hero-art__path"><span /><span /><span /></div><div className="hero-art__badge"><Sparkles aria-hidden="true" size={16} /> Made for student life</div></div>
    </div></section>
    <section aria-labelledby="capabilities-title" className="section section--capabilities" id="what-you-can-do"><div className="page-container"><SectionHeading titleId="capabilities-title" centered eyebrow="A little more clarity" title="Support for the moments that matter">A useful starting point when something feels unfamiliar, confusing, or important.</SectionHeading><div className="capability-grid">{capabilities.map(({ icon: Icon, title, text }, index) => <article className="capability-card" key={title}><div className={`capability-card__icon capability-card__icon--${index + 1}`}><Icon aria-hidden="true" size={23} /></div><h3>{title}</h3><p>{text}</p><span aria-hidden="true" className="capability-card__arrow"><ArrowRight size={18} /></span></article>)}</div><p className="section-footnote">Services are being introduced in stages. This preview explains the approach; it does not provide those tools yet.</p></div></section>
    <section aria-labelledby="how-title" className="section section--steps" id="how-it-works"><div className="page-container steps-layout"><SectionHeading titleId="how-title" eyebrow="A steady process" title="Start wherever you are">No jargon, no pressure. Just a clearer way to look at the question in front of you.</SectionHeading><ol className="step-list">{steps.map((step) => <li className="step" key={step.number}><span className="step__number">{step.number}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></li>)}</ol></div></section>
    <section aria-labelledby="approach-title" className="section section--trust" id="our-approach"><div className="page-container trust-panel"><div className="trust-panel__main"><div className="trust-panel__icon"><ShieldCheck aria-hidden="true" size={25} /></div><SectionHeading titleId="approach-title" eyebrow="A thoughtful approach" title="Clarity should come with care">Understand where information comes from, what it can help with, and when a person may be the right next step.</SectionHeading><a className="text-link text-link--strong" href="#trust-details">What matters to us <ArrowRight aria-hidden="true" size={17} /></a></div><div className="trust-points" id="trust-details"><article><span>01</span><div><h3>Useful, not overwhelming</h3><p>Plain language helps you focus on what matters.</p></div></article><article><span>02</span><div><h3>Limits in the open</h3><p>Information is not a legal opinion or a promise of an outcome.</p></div></article><article><span>03</span><div><h3>Your choices stay yours</h3><p>Explore options and decide whether to seek professional support.</p></div></article></div></div></section>
    <section className="closing-cta"><div className="page-container closing-cta__inner"><div><p className="eyebrow">A confident first step</p><h2>Start with what you want to understand.</h2><p>Explore the approach and see how LexAware is being built for students.</p></div><a className="button button--light" href="#what-you-can-do">Explore support <ArrowRight aria-hidden="true" size={18} /></a></div></section>
  </>;
}
