"""expand_knowledge_governance_schema

Revision ID: 45bd284b1395
Revises: 8cba291f6859
Create Date: 2026-09-08 20:04:44.462604

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45bd284b1395"
down_revision: str | Sequence[str] | None = "8cba291f6859"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledge_items",
        sa.Column("category", sa.String(length=80), server_default="general", nullable=False),
    )
    op.add_column("knowledge_items", sa.Column("topic", sa.String(length=120), nullable=True))
    op.add_column(
        "knowledge_items",
        sa.Column("audience", sa.String(length=60), server_default="students", nullable=False),
    )
    op.create_index("ix_knowledge_items_category", "knowledge_items", ["category"], unique=False)
    op.create_index(
        "ix_knowledge_items_jurisdiction_category_status",
        "knowledge_items",
        ["jurisdiction_id", "category", "status"],
        unique=False,
    )
    op.add_column(
        "knowledge_versions",
        sa.Column("title", sa.String(length=300), server_default="", nullable=False),
    )
    op.add_column("knowledge_versions", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column("knowledge_versions", sa.Column("applicability_notes", sa.Text(), nullable=True))
    op.add_column("knowledge_versions", sa.Column("escalation_guidance", sa.Text(), nullable=True))
    op.add_column(
        "knowledge_versions", sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "knowledge_versions",
        sa.Column("effective_until", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("knowledge_versions", sa.Column("reviewed_by_id", sa.Uuid(), nullable=True))
    op.add_column(
        "knowledge_versions", sa.Column("review_due_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("knowledge_versions", sa.Column("published_by_id", sa.Uuid(), nullable=True))
    op.add_column(
        "knowledge_versions", sa.Column("change_summary", sa.String(length=500), nullable=True)
    )
    op.create_index(
        "ix_knowledge_versions_effective_dates",
        "knowledge_versions",
        ["effective_from", "effective_until"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_versions_item_state",
        "knowledge_versions",
        ["knowledge_item_id", "publication_state"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_versions_review_due_at", "knowledge_versions", ["review_due_at"], unique=False
    )
    op.create_foreign_key(
        None, "knowledge_versions", "users", ["reviewed_by_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "knowledge_versions", "users", ["published_by_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "knowledge_versions", type_="foreignkey")
    op.drop_constraint(None, "knowledge_versions", type_="foreignkey")
    op.drop_index("ix_knowledge_versions_review_due_at", table_name="knowledge_versions")
    op.drop_index("ix_knowledge_versions_item_state", table_name="knowledge_versions")
    op.drop_index("ix_knowledge_versions_effective_dates", table_name="knowledge_versions")
    op.drop_column("knowledge_versions", "change_summary")
    op.drop_column("knowledge_versions", "published_by_id")
    op.drop_column("knowledge_versions", "review_due_at")
    op.drop_column("knowledge_versions", "reviewed_by_id")
    op.drop_column("knowledge_versions", "effective_until")
    op.drop_column("knowledge_versions", "effective_from")
    op.drop_column("knowledge_versions", "escalation_guidance")
    op.drop_column("knowledge_versions", "applicability_notes")
    op.drop_column("knowledge_versions", "summary")
    op.drop_column("knowledge_versions", "title")
    op.drop_index("ix_knowledge_items_jurisdiction_category_status", table_name="knowledge_items")
    op.drop_index("ix_knowledge_items_category", table_name="knowledge_items")
    op.drop_column("knowledge_items", "audience")
    op.drop_column("knowledge_items", "topic")
    op.drop_column("knowledge_items", "category")
    # ### end Alembic commands ###
