"""remove_redundant_user_credentials_email_index

Revision ID: 8cba291f6859
Revises: 7927febec3bb
Create Date: 2026-09-05 11:21:16.413846

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cba291f6859"
down_revision: str | Sequence[str] | None = "7927febec3bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_credentials_email"), table_name="user_credentials")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_user_credentials_email"), "user_credentials", ["email"], unique=False)
    # ### end Alembic commands ###
